### PR TITLE
adding WikiProject Paranormal

### PR DESCRIPTION
**Pull request by SeanFromIT**
Link to my live site, if you're interested.

### CODE REVIEW

**Comment by sbrl** [comment]
Hey there - thanks for the link! That's an unusual wiki. While I do not believe that such paranormal things as documented on that wiki exist (and hence I'm somewhat hesitant to add it to to the main README list), the articles you have there seem relatively well grounded in real science - so I'm inclined to allow the merge here.

**Comment by SeanFromIT** [comment]
Unrelated but seems to have auto-updated this PR: changed phrasing on one of the error messages.

**Comment by sbrl** [comment]
Thanks! To merge this then could you put in a comment that  you agree to release your contribution under the MPL-2.0 please?

**Comment by SeanFromIT** [comment]
I agree to release the contribution under the MPL-2.0

**Pull request merged**
